---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kmons
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./overlay/docker
  prune: true
  sourceRef:
    kind: GitRepository
    name: kmons
  targetNamespace: monitoring
