---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kmons
  namespace: flux-system
spec:
  interval: 60s
  ref:
    branch: main
  url: https://github.com/VtG242/KMONS
